import "./globals.css";
import SupabaseProvider from "./supabase-provider";

import Login from "./Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <SupabaseProvider>
          <Login />
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
};

export default RootLayout;
